# Copyright 2006 The Android Open Source Project

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_AP_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_AP_ARG=\"$(WIFI_DRIVER_MODULE_AP_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif
ifdef WIFI_DRIVER_LOADER_DELAY
LOCAL_CFLAGS += -DWIFI_DRIVER_LOADER_DELAY=$(WIFI_DRIVER_LOADER_DELAY)
endif
ifdef WIFI_DRIVER_FW_PATH_STA
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_STA=\"$(WIFI_DRIVER_FW_PATH_STA)\"
endif
ifdef WIFI_DRIVER_FW_PATH_AP
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_AP=\"$(WIFI_DRIVER_FW_PATH_AP)\"
endif
ifdef WIFI_DRIVER_FW_PATH_P2P
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_P2P=\"$(WIFI_DRIVER_FW_PATH_P2P)\"
endif
ifdef WIFI_DRIVER_FW_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_PARAM=\"$(WIFI_DRIVER_FW_PATH_PARAM)\"
endif
ifdef WIFI_EXT_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_EXT_MODULE_PATH=\"$(WIFI_EXT_MODULE_PATH)\"
endif
ifdef WIFI_EXT_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_EXT_MODULE_ARG=\"$(WIFI_EXT_MODULE_ARG)\"
endif
ifdef WIFI_EXT_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_EXT_MODULE_NAME=\"$(WIFI_EXT_MODULE_NAME)\"
endif

#ifeq ($(strip $(BOARD_WIFI_VENDOR)),realtek)
#LOCAL_SRC_FILES += ../../device/actions/gs702a/hardware/wlan/rtl8188eu/libhardware_legacy/wifi/wifi_realtek.c
#else ifeq ($(strip $(BOARD_WIFI_VENDOR)), mt6620)
#LOCAL_SRC_FILES += ../../device/actions/gs702a/hardware/mtk4in1/wifi/libhardware_legacy/wifi/mtk_wifi.c
#LOCAL_CFLAGS += -DMTK_WLAN_SUPPORT=\"$(MTK_WLAN_SUPPORT)\"
#else ifeq ($(strip $(BOARD_WIFI_VENDOR)), mt5931)
#LOCAL_SRC_FILES += ../../device/actions/gs702a/hardware/wifi/mt5931/libhardware_legacy/wifi/mtk_wifi.c
#LOCAL_CFLAGS += -DMTK_WLAN_SUPPORT=\"$(MTK_WLAN_SUPPORT)\"
#else
LOCAL_SRC_FILES += wifi/wifi.c
ifeq ($(BOARD_HAVE_SAMSUNG_WIFI),true)
LOCAL_CFLAGS += -DSAMSUNG_WIFI
endif
#endif

ifeq ($(BOARD_HAVE_SAMSUNG_WIFI),true)
LOCAL_CFLAGS += -DSAMSUNG_WIFI
endif

LOCAL_SHARED_LIBRARIES += libnetutils
